WIP: lilic/add webserver
kinvolk/mountinfo-graph pull request #2
Opened 2016-09-14 12:58 UTC by LiliC

**What:** Parsing /mountinfo from different mount namespaces and representing the information as a graph using D3.

**Current status:** It takes user input and in a new page displays generated tree using d3. 

Would love to get suggestions how to handle errors better, as well as overall feedback and any other suggestions always welcome.

-
Note that FE part is still WIP and some commits are for Heroku deployment.

2016-09-14 13:02 UTC, LiliC commented on main.go
> +	"./migraph"
this works for me, but I noticed its not best practice, suggestions welcome....

2016-09-14 13:04 UTC, alban commented on Godeps/Godeps.json
> +	"ImportPath": "github.com/lilic/mountinfo",
It seems to be the wrong URL: 404

2016-09-14 13:07 UTC, alban commented on Godeps/Godeps.json
> +	"ImportPath": "github.com/lilic/mountinfo",
same for vendor/vendor.json

Also I guess we don't need both Godeps.json and vendor.json but only one of them

2016-09-14 13:07 UTC, LiliC commented on Godeps/Godeps.json
> +	"ImportPath": "github.com/lilic/mountinfo",
aha yes it was autogenerated `github.com/kinvolk/mountinfo-graph` this would be the correct one then?

2016-09-14 13:10 UTC, alban commented on Godeps/Godeps.json
> +	"ImportPath": "github.com/lilic/mountinfo",
Yes, should be.

2016-09-14 13:14 UTC, krnowak commented on main.go
> +	"./migraph"
I'm getting `can't load package: /home/kv/projects/kinvolk/GOPATH/src/github.com/kinvolk/mountinfo-graph/main.go:4:2: local import "./migraph" in non-local package`, so I think you should replace it with `"github.com/kinvolk/mountinfo-graph/migraph"`.

2016-09-14 13:18 UTC, krnowak commented on main.go
> +	t, err := template.ParseFiles("index.html")
This is a bit troublesome as this requires the `index.html` file to be in the current running directory. Making the contents of the `index.html` file a string const stored in a separate `.go` file would make the program to be standalone.

2016-09-14 13:30 UTC, krnowak commented on main.go
> +	t, err := template.ParseFiles("show.html")
Same here.

2016-09-14 13:33 UTC, LiliC commented on main.go
> +	"./migraph"
@krnowak thanks! Also I noticed there is sometimes a empty line after the package names starting with `github.com/...`, should there be one here as well?

2016-09-15 11:29 UTC, lilic commented on main.go
> +	t, err := template.ParseFiles("index.html")
@krnowak can you have another look, thanks :)

2016-09-15 12:16 UTC, krnowak commented on index.html
> +<!doctype html>
This file is redundant, we already have this in bindata package.

2016-09-15 12:20 UTC, krnowak commented on main.go
> +	t, err := template.New("index").Parse(bindata.Index())
You could probably put the contents of this function into `func generateFromTemplate(htmlTemplate string, body string)` and then use the new function in both `indexHandler` and `showHandler`.

2016-09-15 12:28 UTC, krnowak commented on main.go
> +	//TODO: handle errors
Well, then handle them. :) At this point it would basically be `log.Fatalf("failed to listen and serve: %v", err)` and that's it.

2016-09-15 12:28 UTC, krnowak commented on show.html
> +<!DOCTYPE html>
This is redundant too.

2016-09-15 12:31 UTC, krnowak requested changes
Looks mostly fine, just mostly minor nits.

2016-09-16 07:26 UTC, LiliC commented
@krnowak thanks, I addressed your comments, although it seems github does not collapse them anymore even if they are outdated...

2016-09-16 09:18 UTC, krnowak commented on main.go
> +func generateFromTemplate(htmlTemplate string, w http.ResponseWriter, body string) {
My idea was to rather pass the result of either `bindata.Index()` or `bindata.Show()` to the `htmlTemplate` parameter, so the map in the function would not be necessary. But now I can see that we also need a name for the template. Question is whether this name is important for us now. If it is not, you could just hardcode some string there like `t, err := template.New("not important").Parse(htmlTemplate)`.

If the name is important, then you could modify the `bindata` functions to return two strings - a name and data and then forward those to the `generateFromTemplate` function.

2016-09-16 12:10 UTC, LiliC commented on main.go
> +func generateFromTemplate(htmlTemplate string, w http.ResponseWriter, body string) {
@krnowak yes that makes more sense, will try with non unique name first... thanks!

2016-09-16 13:54 UTC, LiliC commented on main.go
> +func generateFromTemplate(htmlTemplate string, w http.ResponseWriter, body string) {
@krnowak done, thanks!

2016-12-02 15:45 UTC, merged